when:
  - event: push
    branch: main

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      depth: 0

steps:
  - name: release-plz
    image: marcoieni/release-plz
    environment:
      RELEASE_PLZ_TOKEN:
        from_secret: release_plz_token
    commands:
      - release-plz release-pr --forge gitea --git-token $RELEASE_PLZ_TOKEN
      - release-plz release --forge gitea --git-token $RELEASE_PLZ_TOKEN
