when:
  - event: push
    branch: main
  - event: pull_request

steps:
  - name: test
    image: rust:1.93.1
    commands:
      - rustup default stable
      - rustup component add clippy
      - cargo clippy -j 4
      - cargo check -j 4
      - cargo test -j 4
